## Author

- **Name:** Min-Hsueh Chiang, JiaLong Li
- **Email:** mchiang5@illinois.edu, jialong7@illinois.edu

## Purpose
The US job market has contracted in 2022 due to pandemic issues and economic recession. Since we are international students, it is more difficult for us to seek an ideal job in the US. Thus, we decided to build an app to display current working position that is open in the US federal job market. Moreover, since we major in statistics, most of the jobs we seek would focus on analyzing data or programming. Thus, the dataset we collected from the website generally focused only on data-oriented jobs. 


## Data
The data is from https://data.usajobs.gov. The data generally describes various jobs across the USA, including jobs in data science, programming, Economist…etc. The dataset that we retrieved contains several different lists of information inside a vast list, and we decided only to retrieve parts that we are interested in, which include the Job’s position; the Job’s location; the organization that is hiring, the minimum wage & maximum wage of the Job; the GPA requirement of the Job, and the educational degree requirement of the Job (Bachelor, Master or Doctoral degree). 


